ymer/src/main/java/com/avanza/ymer/YmerSpaceDataSource.java, ymer/src/test/java/com/avanza/ymer/YmerSpaceDataSourceTest.java
Added a test for this as well.
=> Added timing information for how long individual collections take.

ymer/src/main/java/com/avanza/ymer/DocumentDb.java, ymer/src/main/java/com/avanza/ymer/MirroredObject.java, ymer/src/main/java/com/avanza/ymer/MirroredObjectDefinition.java, ymer/src/main/java/com/avanza/ymer/SpaceMirrorContext.java, ymer/src/main/java/com/avanza/ymer/YmerFactory.java, ymer/src/test/java/com/avanza/ymer/FakeDocumentDb.java, ymer/src/test/java/com/avanza/ymer/MirroredObjectWriterTest.java, ymer/src/test/java/com/avanza/ymer/MongoDocumentCollectionTest.java, ymer/src/test/java/com/avanza/ymer/YmerFactoryTest.java
Cherry-picked commits from https://github.com/AvanzaBank/ymer/pull/13 , but for the `gs14` branch.
=> TP-360: Enable reading from mongo secondaries

pom.xml
Added surefire plugin config to prefer IPv4 to avoid problems with embedded spaces during testing.
=> Added surefire plugin config to prefer IPv4

pom.xml, ymer-test/pom.xml, ymer/src/test/java/com/avanza/ymer/DocumentPatchChainTest.java
* Updated slf4j to 1.7.25
* Updated mockito to 2.23.0
* Updated gs-test to 14.0.3
* Downgraded spring-data-mongodb to 1.10.15.RELEASE
* Clean-up
=> Updates dependencies and maven plugins versions

ymer/src/main/java/com/avanza/ymer/Plugins.java, ymer/src/test/java/com/avanza/ymer/PluginsTest.java
Same as https://github.com/AvanzaBank/ymer/pull/29 but for Java 8 
* Omitted test as the issue is not reproducible with Java 8.
=> TP-525: Avoid ConcurrentModificationException (Java8)

pom.xml, ymer/src/test/java/com/avanza/ymer/YmerFactoryTest.java
Updates:
* mongo-java-driver to 3.4.3
* fongo to 2.1.1
* spring-data-mongodb to 1.8.6.RELEASE
=> TP-251: Update mongo-java-driver to 3.4.3 

ymer/src/main/java/com/avanza/ymer/support/CurrencyReadConverter.java, ymer/src/main/java/com/avanza/ymer/support/CurrencyWriteConverter.java, ymer/src/main/java/com/avanza/ymer/support/JavaLocalDateReadConverter.java, ymer/src/main/java/com/avanza/ymer/support/JavaLocalDateTimeReadConverter.java, ymer/src/main/java/com/avanza/ymer/support/JavaLocalDateTimeWriteConverter.java, ymer/src/main/java/com/avanza/ymer/support/JavaLocalDateWriteConverter.java
Merges current `master` into `gs14` branch.
Reason for merging is to get the same set of converters in the both branches.
=> TP-590: Merge master into gs14

ymer/src/main/java/com/avanza/ymer/Plugins.java, ymer/src/main/java/com/avanza/ymer/support/CurrencyReadConverter.java, ymer/src/main/java/com/avanza/ymer/support/CurrencyWriteConverter.java, ymer/src/main/java/com/avanza/ymer/support/JavaLocalDateReadConverter.java, ymer/src/main/java/com/avanza/ymer/support/JavaLocalDateTimeReadConverter.java, ymer/src/main/java/com/avanza/ymer/support/JavaLocalDateTimeWriteConverter.java, ymer/src/main/java/com/avanza/ymer/support/JavaLocalDateWriteConverter.java, ymer/src/test/java/com/avanza/ymer/PluginsTest.java, ymer/src/test/java/com/avanza/ymer/YmerFactoryTest.java
* Merges `gs14` branch into `gs14.5` branch.
=> TP-590: merge gs14 to gs14.5

ymer/src/main/java/com/avanza/ymer/DocumentPatch.java, ymer/src/main/java/com/avanza/ymer/MirroredObjectDefinition.java, ymer/src/main/java/com/avanza/ymer/plugin/Plugin.java
This PR fixes javadoc compile errors and some minor warnings
=> TP-625: Fixed Javadoc errors

pom.xml, ymer-test/src/main/java/com/avanza/ymer/YmerMigrationTestBase.java
This PR fixes javadoc errors in ymer-test and updated project to always run `maven-javadoc-plugin`, and therefore moved its configuration to pluginManagement
=> TP-625: Fixed javadoc errors in ymer test

pom.xml
=> Configure maven-compiler-plugin to fail on warnings

ymer/src/test/java/com/avanza/ymer/YmerMirrorIntegrationTest.java
Integration test verifying that updating an object field to null works properly.
=> TP-755: Test updating existing object with null field

pom.xml, ymer-test-junit4/src/main/java/com/avanza/ymer/YmerConverterTestBase.java, ymer-test-junit5/src/main/java/com/avanza/ymer/test/YmerConverterTestBase.java, ymer/src/main/java/com/avanza/ymer/MongoDocumentCollection.java, ymer/src/main/java/com/avanza/ymer/YmerFactory.java
* Align spring-data-mongodb with Spring version
* Align mongo-java-driver with Spring-data version
* Update deprecated code
* Minor updates of other dependencies
=> Update mongo-java-driver dependency

.github/workflows/build.yml, .travis.yml, README.md
TP-870: GitHub workflow for building, running tests and publishing test report.
=> TP-870: CI build using GitHub actions

pom.xml
TP-911: Update Log4j to 2.15.0, see https://logging.apache.org/log4j/2.x/changes-report.html#a2.15.0
=> TP-911: Update Log4j to 2.15.0

examples/example-pu/src/main/java/example/mirror/ExampleMirrorFactory.java, examples/example-pu/src/test/java/example/mirror/ExampleMirrorConverterTest.java, examples/example-tests/src/test/java/example/tests/InitialLoadTest.java, examples/example-tests/src/test/java/example/tests/SpaceObjectWriteSynchronizationTest.java, pom.xml, ymer-test-junit4/src/main/java/com/avanza/ymer/YmerConverterTestBase.java, ymer-test-junit4/src/test/java/com/avanza/ymer/ExampleYmerConverterTest.java, ymer-test-junit4/src/test/java/com/avanza/ymer/YmerConverterTestBaseTest.java, ymer-test-junit5/src/main/java/com/avanza/ymer/test/YmerConverterTestBase.java, ymer-test-junit5/src/test/java/com/avanza/ymer/test/YmerConverterTestBaseTest.java, ymer/pom.xml, ymer/src/main/java/com/avanza/ymer/DocumentCollection.java, ymer/src/main/java/com/avanza/ymer/YmerFactory.java, ymer/src/main/java/com/avanza/ymer/util/GigaSpacesInstanceIdUtil.java, ymer/src/test/java/com/avanza/ymer/ConverterTest.java, ymer/src/test/java/com/avanza/ymer/MirrorEnvironment.java, ymer/src/test/java/com/avanza/ymer/PersistedInstanceIdCalculationServiceTest.java, ymer/src/test/java/com/avanza/ymer/TestSpaceMirrorFactory.java, ymer/src/test/java/com/avanza/ymer/TestSpaceMongoConverterFactory.java, ymer/src/test/java/com/avanza/ymer/YmerFactoryTest.java, ymer/src/test/java/com/avanza/ymer/YmerMirrorNoClusterPropertiesIntegrationTest.java
TP-963: Update Gigaspaces to 16.1.0, Spring Framework to 5.3.7, Spring Data MongoDB to 3.2.1
Use mongodb-java-driver-sync 4.2.3 instead of mongo-java-driver 3.8.2
=> TP-963: Support for Gigaspaces 16

ymer/src/main/java/com/avanza/ymer/support/JavaYearMonthReadConverter.java, ymer/src/main/java/com/avanza/ymer/support/JavaYearMonthWriteConverter.java, ymer/src/test/java/com/avanza/ymer/support/JavaYearMonthConverterTest.java, ymer/src/test/java/com/avanza/ymer/support/JavaYearMonthReadConverterTest.java, ymer/src/test/java/com/avanza/ymer/support/JavaYearMonthWriteConverterTest.java
Added YearMonth converter (thanks @Wallman!)
(cherry picked from commit b70aee1200b2a50d5dab0ff18e92eababcb3f79b)
=> YearMonth converters (GS16)

examples/example-pu/src/main/java/example/mirror/SpaceFruitV1ToV2Patch.java, examples/example-tests/pom.xml, pom.xml, ymer-test-junit4/src/test/java/com/avanza/ymer/YmerMigrationTestBaseTest.java, ymer-test-junit5/src/test/java/com/avanza/ymer/test/YmerMigrationTestBaseTest.java, ymer/pom.xml, ymer/src/main/java/com/avanza/ymer/DocumentPatch.java, ymer/src/test/java/com/avanza/ymer/BsonDocumentPatchTest.java, ymer/src/test/java/com/avanza/ymer/DocumentPatchApplyTest.java, ymer/src/test/java/com/avanza/ymer/DocumentPatchChainTest.java, ymer/src/test/java/com/avanza/ymer/MirroredObjectLoaderTest.java, ymer/src/test/java/com/avanza/ymer/MirroredObjectTest.java, ymer/src/test/java/com/avanza/ymer/MirroredObjectWriterTest.java, ymer/src/test/java/com/avanza/ymer/MirroredObjectsTest.java, ymer/src/test/java/com/avanza/ymer/MongoDocumentCollectionTest.java, ymer/src/test/java/com/avanza/ymer/TestSpaceThirdObject.java, ymer/src/test/java/com/avanza/ymer/YmerInitialLoadIntegrationTest.java, ymer/src/test/java/com/avanza/ymer/YmerSpaceDataSourceTest.java
Use `BsonDocumentPatch` in tests, where applicable.
=> TP-1083: Deprecate DocumentPatch

.github/workflows/build.yml, ymer/src/test/java/com/avanza/ymer/MirrorEnvironment.java, ymer/src/test/java/com/avanza/ymer/YmerMirrorIntegrationTest.java, ymer/src/test/resources/log4j2.xml
* This verifies that the integration tests passes against multiple MongoDB versions using github workflows
=> Run integration tests against multiple mongodb versions

ymer/src/main/java/com/avanza/ymer/MirroredObjectWriter.java, ymer/src/main/java/com/avanza/ymer/PerMinuteCounter.java, ymer/src/main/java/com/avanza/ymer/PerformedOperationMetrics.java, ymer/src/main/java/com/avanza/ymer/PerformedOperationMetricsMBean.java, ymer/src/main/java/com/avanza/ymer/PerformedOperationsListener.java, ymer/src/main/java/com/avanza/ymer/YmerFactory.java, ymer/src/main/java/com/avanza/ymer/YmerSpaceSynchronizationEndpoint.java, ymer/src/test/java/com/avanza/ymer/PerMinuteCounterTest.java, ymer/src/test/java/com/avanza/ymer/YmerMirrorIntegrationTest.java
Adds a new MBean that exports the number of mongo operations (inserts/updates/deletes and the total number)
Naming classes is always hard, feedback is welcome
=> TP-1208 Add mbean exposing number of performed mongo operations

.github/workflows/build.yml, pom.xml, ymer/pom.xml, ymer/src/test/java/com/avanza/ymer/IdValidatorImplTest.java, ymer/src/test/java/com/avanza/ymer/MirrorEnvironment.java, ymer/src/test/java/com/avanza/ymer/MongoDocumentCollectionTest.java, ymer/src/test/java/com/avanza/ymer/MongoPartitionFilterTest.java
* Suggest that we switch out Fongo for testcontainers in legacy branch as well
* Run tests against multiple Mongo versions
=> Use testcontainers in v1.4.x

.github/workflows/build.yml, pom.xml, ymer/pom.xml, ymer/src/main/java/com/avanza/ymer/MirroredObjectWriter.java, ymer/src/main/java/com/avanza/ymer/PerMinuteCounter.java, ymer/src/main/java/com/avanza/ymer/PerformedOperationMetrics.java, ymer/src/main/java/com/avanza/ymer/PerformedOperationMetricsMBean.java, ymer/src/main/java/com/avanza/ymer/PerformedOperationsListener.java, ymer/src/main/java/com/avanza/ymer/YmerFactory.java, ymer/src/main/java/com/avanza/ymer/YmerSpaceSynchronizationEndpoint.java, ymer/src/test/java/com/avanza/ymer/IdValidatorImplTest.java, ymer/src/test/java/com/avanza/ymer/MirrorEnvironment.java, ymer/src/test/java/com/avanza/ymer/MongoDocumentCollectionTest.java, ymer/src/test/java/com/avanza/ymer/MongoPartitionFilterTest.java, ymer/src/test/java/com/avanza/ymer/PerMinuteCounterTest.java, ymer/src/test/java/com/avanza/ymer/YmerMirrorIntegrationTest.java
Merge operation statistics mbean code from main branch. See https://github.com/AvanzaBank/ymer/pull/96
=> TP-1208 merge operation statistics mbean from main
