- README.md
- examples/example-pu/src/test/java/example/mirror/ExampleMirrorConverterTest.java
- ymer-test/src/main/java/com/avanza/ymer/YmerConverterTestBase.java
- ymer-test/src/test/java/com/avanza/ymer/YmerConverterTestBaseTest.java
Method in YmerConverterTestBase is incorrectly named getMirroredDocumentDefinitions (from persistence-support). It should be named getMirroredObjectDefinitions as in YmerMigrationTestBase.
> Renamed getMirroredDocumentDefinitions to getMirroredObjectDefinitions in YmerConverterTestBase

- ymer/src/main/java/com/avanza/ymer/DocumentDb.java
- ymer/src/main/java/com/avanza/ymer/MirroredObject.java
- ymer/src/main/java/com/avanza/ymer/MirroredObjectDefinition.java
- ymer/src/main/java/com/avanza/ymer/SpaceMirrorContext.java
- ymer/src/main/java/com/avanza/ymer/YmerFactory.java
- ymer/src/test/java/com/avanza/ymer/FakeDocumentDb.java
- ymer/src/test/java/com/avanza/ymer/MirroredObjectWriterTest.java
- ymer/src/test/java/com/avanza/ymer/MongoDocumentCollectionTest.java
- ymer/src/test/java/com/avanza/ymer/YmerFactoryTest.java
Adds two new abilities:
* Configure the `YmerFactory` so that all document queries may be read from mongo secondaries.
* Configure each `MirroredObjectDefinition` with an explicit readpreference, so that documents may be read from mongo secondaries
This will be used in cases where a lot of data needs to be loaded, and we want to reduce the load on the primary mongo instance.
> TP-360: enable reading from secondaries

- pom.xml
Updated multiple maven plugins, especially org.codehaus.mojo:versions-maven-plugin from 1.2 to 2.5
> TP-393: Updated maven plugin versions

- ymer/src/test/java/com/avanza/ymer/FakeDocumentCollection.java
* Prevents the following test failure:
```
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.122 s <<< FAILURE! - in com.avanza.ymer.YmerSpaceDataSourceTest
[ERROR] documentsMustNotBeWrittenToDbBeforeAllElementsAreLoaded(com.avanza.ymer.YmerSpaceDataSourceTest) Time elapsed: 0.01 s <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<2>
at com.avanza.ymer.YmerSpaceDataSourceTest.documentsMustNotBeWrittenToDbBeforeAllElementsAreLoaded(YmerSpaceDataSourceTest.java:73)
```
The reason for the test previously failing is as follows:
* `YmerSpaceDataSource::load` calls `documentLoader.streamAllObjects()`, that returns a stream of all documents.
* This stream is traversed, and each object gets passed to `createPatchedDocumentWriteBack`, which in turn calls …
> TP-394: Fix failing test YmerSpaceDataSourceTest

- ymer/src/main/java/com/avanza/ymer/support/JavaInstantReadConverter.java
- ymer/src/main/java/com/avanza/ymer/support/JavaInstantWriteConverter.java
- ymer/src/test/java/com/avanza/ymer/support/JavaInstantConverterTest.java
- ymer/src/test/java/com/avanza/ymer/support/JavaInstantReadConverterTest.java
- ymer/src/test/java/com/avanza/ymer/support/JavaInstantWriteConverterTest.java
Notes to reviewer:
* Instant will always use the UTC time zone, meaning that all strings written as a `String` will always been in UTC format, and it is up to the user of a given `Instant` to set the appropriate time zone. 
* The converters need to be added explicit as custom converters in a given space/PU that want to use them.
> TP-419: Added Read- and WriteConverter for java.time.Instant with nano precision

- examples/example-pu/src/main/java/example/mirror/SpaceFruitV1ToV2Patch.java
- ymer-test/src/test/java/com/avanza/ymer/YmerMigrationTestBaseTest.java
- ymer/src/main/java/com/avanza/ymer/BsonDocumentPatch.java
- ymer/src/main/java/com/avanza/ymer/DocumentPatchChain.java
- ymer/src/main/java/com/avanza/ymer/MirroredObject.java
- ymer/src/main/java/com/avanza/ymer/MirroredObjectDefinition.java
- ymer/src/test/java/com/avanza/ymer/DocumentPatchChainTest.java
- ymer/src/test/java/com/avanza/ymer/MirroredObjectLoaderTest.java
- ymer/src/test/java/com/avanza/ymer/MirroredObjectTest.java
- ymer/src/test/java/com/avanza/ymer/TestSpaceMirrorObjectDefinitions.java
- ymer/src/test/java/com/avanza/ymer/TestSpaceThirdObject.java
- ymer/src/test/java/com/avanza/ymer/YmerInitialLoadIntegrationTest.java
- ymer/src/test/java/com/avanza/ymer/YmerSpaceDataSourceTest.java
* Adds class `BsonDocumentPatch` that is intended to replace the previous `DocumentPatch`, but that takes a `Document` instead of `BasicDBObject`.
* Adds compatibility code in `DocumentPatch` so that existing code that uses it can still work, even if the underlying data store is a `Document`.
* Adds unit tests that verify that both types of patch classes work.
> TP-426: Use different interfaces for DocumentPatch

- ymer/src/main/java/com/avanza/ymer/Plugins.java
- ymer/src/test/java/com/avanza/ymer/PluginsTest.java
This MR contains two implementation suggestions split up into separate commits for discussion:
1) https://github.com/AvanzaBank/ymer/pull/29/commits/c4270216eb1b555104f707110c78eacf918b10b1
Simply replaces `HashMap` with `ConcurrentHashMap` to switch implementation of method `computeIfAbsent()`
2) https://github.com/AvanzaBank/ymer/pull/29/commits/627298333b128968b642a7552ae882b27bfe8188
This implementation replaces the usage of `computeIfAbsent()` with an explicit implementation instead, for the same behaviour.
> TP-525: Avoid ConcurrentModificationException

- pom.xml
- ymer/src/test/java/com/avanza/ymer/YmerFactoryTest.java
Same as #32 , but for gs14.
Updates:
* mongo-java-driver to 3.4.3
* fongo to 2.1.1
Does not update
* spring-data-mongodb to 1.8.6.RELEASE ( it was already at this version in this branch ).
> TP-251: Update mongo-java-driver to 3.4.3 (gs14)

- ymer/src/main/java/com/avanza/ymer/support/JavaInstantReadConverter.java
- ymer/src/main/java/com/avanza/ymer/support/JavaInstantWriteConverter.java
- ymer/src/test/java/com/avanza/ymer/support/JavaInstantConverterTest.java
- ymer/src/test/java/com/avanza/ymer/support/JavaInstantReadConverterTest.java
- ymer/src/test/java/com/avanza/ymer/support/JavaInstantWriteConverterTest.java
* Backports `Instant` converters from `gs14` branch back to `master`, to keep the same converters available in both branches.
* Originally created in https://github.com/AvanzaBank/ymer/pull/23
> TP-590: Backport Instant-converters from gs14 branch

- ymer/src/main/java/com/avanza/ymer/support/CurrencyReadConverter.java
- ymer/src/main/java/com/avanza/ymer/support/CurrencyWriteConverter.java
- ymer/src/main/java/com/avanza/ymer/support/JavaInstantReadConverter.java
- ymer/src/main/java/com/avanza/ymer/support/JavaInstantWriteConverter.java
- ymer/src/main/java/com/avanza/ymer/support/JavaLocalDateReadConverter.java
- ymer/src/main/java/com/avanza/ymer/support/JavaLocalDateTimeReadConverter.java
- ymer/src/main/java/com/avanza/ymer/support/JavaLocalDateTimeWriteConverter.java
- ymer/src/main/java/com/avanza/ymer/support/JavaLocalDateWriteConverter.java
- ymer/src/main/java/com/avanza/ymer/support/JavaTimeLocalDateTimeReadConverter.java
- ymer/src/main/java/com/avanza/ymer/support/JavaTimeLocalDateTimeWriteConverter.java
- ymer/src/test/java/com/avanza/ymer/ConverterTest.java
* Explicitly sets the type of converion expected by the ymer built-in custom converters.
* Reason for setting is to prevent that the "from string to (something)" converters are used by default when writing data to the db, such as the `LocalDateTimeReadConverter`.
* Now, instead, only the `WritingConverter`s will be used when writing data. This means that string data will not get mangled by the custom converters.
* This commit prevents exceptions such as the following:
```
2021-03-04 13:52:04,267 [GS-LRMI Connection-pool-1-thread-2] ERROR RethrowsTransientDocumentWriteExceptionHandler Exception when executing mirror command! Attempted operation: Operation: INSERT, objects: [[SpaceFilePublicationEvent{id='A1^1111111111111111^3', time=2021-03-04T13:52:02.405924, file='accounts'}]] - This …
```
> TP-620: Prevent using "from string" converters when writing db data

- ymer-test/src/main/java/com/avanza/ymer/YmerMigrationTestBase.java
- ymer-test/src/test/java/com/avanza/ymer/YmerMigrationTestBaseTest.java
* Updates `MigrationTest` so that it also accepts the old `BasicDBObject` types in migration unit tests.
* Reason for still allowing them is to make it easier for apps to partially migrate source to using `Document` instead.
* With this commit, an implementing app will not have to make code-changes to tests in order to compile (even making such changes would be preferable).
> Also accept old-style BasicDBObject in MigrationTest

- pom.xml
- ymer-test/pom.xml
- ymer/pom.xml
This PR updates `hamcrest` to version 2.2 and reorders test dependencies as instructed in the hamcrest upgrade instructions:
* http://hamcrest.org/JavaHamcrest/distributables#maven-upgrade-example
> TP-630: Updated hamcrest version to 2.2 

- ymer/src/main/java/com/avanza/ymer/DocumentPatch.java
- ymer/src/test/java/com/avanza/ymer/DocumentPatchApplyTest.java
This PR updates `DocumentPatch` with a fix to `DocumentPatch#apply(Document)` that ensures that properties that have been removed by the applied patch are also removed in the patched `Document`.
This problem only affected projects with patches initially. based on `BasicDBObject` and are migrated to use Document in later patches.
> TP-639: Ensure that properties are removed correctly with DocumentPatch

- pom.xml
- ymer-test/src/test/java/com/avanza/ymer/YmerMigrationTestBaseTest.java
- ymer/src/main/java/com/avanza/ymer/DocumentDb.java
- ymer/src/test/java/com/avanza/ymer/YmerFactoryTest.java
* How to disable the javadoc warnings in the maven-javadoc-plugin was changed in v3.0.0.
* Other warnings have been suppressed.
> TP-636 - Remove all Ymer compilation warnings

- ymer/src/main/java/com/avanza/ymer/MongoDocumentCollection.java
Fix bug where already persisted objects where fields are updated to null were not getting updated properly. Instead we now replace the whole object instead of updating it in mongo.
> TP-755: Replace object instead of updating so it works with fields updated to null

- ymer/src/main/java/com/avanza/ymer/YmerFactory.java
* Adds a startup warning if the list of mirrored types given to `YmerFactory` is empty.
* Either the app intends to store or load some documents: then it should supply which types.
* Or the app does not intend to store or load documents: the the app should not use ymer.
* The intention of this commit is to provide a troublehooting warning-message in case something is wrong about how the app supplies the list of mirrored documents.
> Warn if list of mirrored types is empty

- ymer-test-junit4/src/main/java/com/avanza/ymer/YmerConverterTestBase.java
- ymer-test-junit4/src/test/java/com/avanza/ymer/ExampleSpaceObjWithInstant.java
- ymer-test-junit4/src/test/java/com/avanza/ymer/ExampleYmerConverterTest.java
- ymer-test-junit4/src/test/java/com/avanza/ymer/YmerMirroredTypesTestBaseTest.java
- ymer-test-junit5/src/main/java/com/avanza/ymer/test/YmerConverterTestBase.java
* Makes the app-provided instance of `MongoConverter` be fully instantiated with its internal `conversionService` field when running unit tests using the converters.
* Fixes issue where, if an app provided an instance of `MongoConverter` that is not created in a spring context but only programmatically in a unit test, the tests that inherit from `YmerConverterTestBase` would not work.
* Resolves the following exception, as seen when running unit tests on an app that provides an instance of `MongoConverter` where `.afterPropertiesSet()` has not yet been called:
```
org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.time.Instant] to type [java.lang.String]	at org.springframework.core.convert.support.GenericConversionService.h …
```
> TP-833: Fully create MongoConverter in unit tests

- ymer/src/main/java/com/avanza/ymer/IdValidatorImpl.java
- ymer/src/main/java/com/avanza/ymer/MongoDocumentCollection.java
- ymer/src/test/java/com/avanza/ymer/IdValidatorImplTest.java
- ymer/src/test/java/com/avanza/ymer/YmerFactoryTest.java
* Adds warning messages when writing documents to MongoDb that do not contain an `_id` field.
* Adds warning messages when MongoDb document operations (insert, update, delete) attempted to affect an existing document, but the `_id` was not found in the database.
* Reason for adding these warnings is to make it obvious for apps that there might be something misconfigured on the mirrored document types, and could lead to data loss if not addressed.
* Not having an `_id` field will auto-populate it by MongoDb when written to db, and the written value is never handled by ymer - and thus will not be replicated to the GigaSpaces space object.
* Trying to update a document for an id that does not exist likely means that the view of which documents exists differs between GigaSpaces and MongoDb.
> TP-824: Warn when mongodb id operations do not match any documents

- pom.xml
- ymer-test-junit4/pom.xml
- ymer-test-junit4/src/main/java/com/avanza/ymer/YmerConverterTestBase.java
- ymer-test-junit4/src/test/java/com/avanza/ymer/YmerConverterTestBaseTest.java
- ymer-test-junit5/pom.xml
- ymer-test-junit5/src/main/java/com/avanza/ymer/test/YmerConverterTestBase.java
- ymer-test-junit5/src/test/java/com/avanza/ymer/test/YmerConverterTestBaseTest.java
This adds a dependency to AsstertJ in order to support comparing nested objects.
If we want to support comparing nested objects, some kind of additional dependency is probably required.
> TP-867: Use AssertJ recursive comparison to support comparing nested objects

- pom.xml
- ymer/pom.xml
- ymer/src/main/java/com/avanza/ymer/DocumentCollection.java
- ymer/src/main/java/com/avanza/ymer/MongoDocumentCollection.java
- ymer/src/main/java/com/avanza/ymer/PersistedInstanceIdRecalculationService.java
- ymer/src/main/java/com/avanza/ymer/PersistedInstanceIdRecalculationServiceMBean.java
- ymer/src/main/java/com/avanza/ymer/YmerFactory.java
- ymer/src/main/java/com/avanza/ymer/YmerSpaceSynchronizationEndpoint.java
- ymer/src/main/java/com/avanza/ymer/util/StreamUtils.java
- ymer/src/test/java/com/avanza/ymer/DocumentCollectionContract.java
- ymer/src/test/java/com/avanza/ymer/FakeDocumentCollection.java
- ymer/src/test/java/com/avanza/ymer/MirroredObjectLoaderTest.java
- ymer/src/test/java/com/avanza/ymer/MongoDocumentCollectionTest.java
- ymer/src/test/java/com/avanza/ymer/PersistedInstanceIdRecalculationServiceTest.java
- ymer/src/test/java/com/avanza/ymer/TestSpaceMirrorObjectDefinitions.java
- ymer/src/test/java/com/avanza/ymer/util/StreamUtilsTest.java
Update documents in batches, to reduce overhead. Use the same batch size for reading documents to update.
> TP-876: Speed up instance id recalculation

- ymer/src/main/java/com/avanza/ymer/MirroredObject.java
- ymer/src/main/java/com/avanza/ymer/MirroredObjectDefinition.java
- ymer/src/main/java/com/avanza/ymer/MirroredObjectDefinitionsOverride.java
- ymer/src/main/java/com/avanza/ymer/PersistInstanceIdDefinition.java
- ymer/src/main/java/com/avanza/ymer/PersistedInstanceIdRecalculationService.java
- ymer/src/main/java/com/avanza/ymer/PersistedInstanceIdRecalculationServiceMBean.java
- ymer/src/main/java/com/avanza/ymer/YmerSpaceSynchronizationEndpoint.java
- ymer/src/test/java/com/avanza/ymer/MirroredObjectLoaderTest.java
- ymer/src/test/java/com/avanza/ymer/MirroredObjectTest.java
- ymer/src/test/java/com/avanza/ymer/MirroredObjectWriterTest.java
- ymer/src/test/java/com/avanza/ymer/PersistedInstanceIdRecalculationServiceTest.java
- ymer/src/test/java/com/avanza/ymer/TestSpaceMirrorObjectDefinitions.java
* Triggers recalculation after a configured delay after application startup
* Default configuration is to execute the recalculation job 60 minutes after startup
* `YmerSpaceSynchronizationEndpoint` needs to be a Spring-managed bean to execute the job at startup
* Properties related to instance id persisting are now grouped in a separate configuration class inspired by Spring Security config
This can create a flowing config like the following example:
```
MirroredObjectDefinition.create(TestSpaceObject.class)
.persistInstanceId()
.recalculateOnStartup(true)
.recalculateWithDelay(3_600)
.and()
.loadDocumentsRouted(true)
```
> TP-828: Trigger recalculation of persisted instance IDs on startup

- ymer/src/main/java/com/avanza/ymer/DocumentCollection.java
- ymer/src/main/java/com/avanza/ymer/InstanceMetadata.java
- ymer/src/main/java/com/avanza/ymer/MirroredObject.java
- ymer/src/main/java/com/avanza/ymer/MirroredObjectDefinitionsOverride.java
- ymer/src/main/java/com/avanza/ymer/MirroredObjectLoader.java
- ymer/src/main/java/com/avanza/ymer/MirroredObjectWriter.java
- ymer/src/main/java/com/avanza/ymer/MongoDocumentCollection.java
- ymer/src/main/java/com/avanza/ymer/PersistInstanceIdDefinition.java
- ymer/src/main/java/com/avanza/ymer/PersistedInstanceIdCalculationService.java
- ymer/src/main/java/com/avanza/ymer/PersistedInstanceIdCalculationServiceMBean.java
- ymer/src/main/java/com/avanza/ymer/PersistedInstanceIdRecalculationService.java
- ymer/src/main/java/com/avanza/ymer/PersistedInstanceIdUtil.java
- ymer/src/main/java/com/avanza/ymer/ReloadableYmerProperties.java
- ymer/src/main/java/com/avanza/ymer/SpaceMirrorContext.java
- ymer/src/main/java/com/avanza/ymer/YmerFactory.java
- ymer/src/main/java/com/avanza/ymer/YmerSpaceSynchronizationEndpoint.java
- ymer/src/main/java/com/avanza/ymer/util/GigaSpacesInstanceIdUtil.java
- ymer/src/test/java/com/avanza/ymer/FakeDocumentCollection.java
- ymer/src/test/java/com/avanza/ymer/MirroredObjectLoaderTest.java
- ymer/src/test/java/com/avanza/ymer/MirroredObjectTest.java
- ymer/src/test/java/com/avanza/ymer/MirroredObjectWriterTest.java
- ymer/src/test/java/com/avanza/ymer/MongoDocumentCollectionTest.java
- ymer/src/test/java/com/avanza/ymer/PersistedInstanceIdCalculationServiceTest.java
- ymer/src/test/java/com/avanza/ymer/PersistedInstanceIdRecalculationServiceTest.java
- ymer/src/test/java/com/avanza/ymer/TestSpaceMirrorFactory.java
- ymer/src/test/java/com/avanza/ymer/YmerMirrorIntegrationTest.java
- ymer/src/test/java/com/avanza/ymer/util/GigaSpacesInstanceIdUtilTest.java
* Next number of instances will now be calculated when configured.
This is done in order to prepare for scaling out to a different amount of instances without having a slow startup.
* In order to store different instanceIds depending on the amount of instances, `_instanceId` field now has a suffix for the amount of instances (e.g. `_instanceId_4`).
* Adds support for reloadable properties (currently only contains next number of instances)
* Next number of instances will be written by mirror when:
-- `PersistedInstanceIdRecalculationService` is called
--Writing new/changing documents
* `PersistedInstanceIdRecalculationService` will now only recalculate objects where `_instanceId` isn't already saved for the current number of partitions. Re-running the job should be much faster than before. …
> TP-820: Add support for calculating next number of instances

- ymer/src/main/java/com/avanza/ymer/MirroredObjectWriter.java
- ymer/src/test/java/com/avanza/ymer/FakeDocumentWriteExceptionHandler.java
- ymer/src/test/java/com/avanza/ymer/MirroredObjectWriterTest.java
* Adds explicit logging of the class name of failed mongodb document operations.
* The intention is that this will simplify troubleshooting when handling classes that do not by themselves write their class names as part of their `.toString()`-output.
> TP-945: Log object class name on exception

- ymer/src/main/java/com/avanza/ymer/PersistedInstanceIdCalculationService.java
- ymer/src/main/java/com/avanza/ymer/PersistedInstanceIdUtil.java
- ymer/src/test/java/com/avanza/ymer/PersistedInstanceIdCalculationServiceTest.java
* This method did not properly check if calculation is needed when nextNumberOfInstances is used. This method only worked when no of the number of partitions to calculate were calculated, but we want to do a calculation when any of them are missing (such as adding a new `nextNumberOfInstances` when current number of instances is already calculated).
Found during review of [another issue](https://github.com/AvanzaBank/ymer/pull/67).
> TP-820: Fix bug in `collectionNeedsCalculation`

- pom.xml
- ymer/src/main/java/com/avanza/ymer/PersistedInstanceIdCalculationService.java
- ymer/src/main/java/com/avanza/ymer/YmerSpaceSynchronizationEndpoint.java
- ymer/src/test/java/com/avanza/ymer/TestSpaceMirrorFactory.java
- ymer/src/test/java/com/avanza/ymer/TestSpaceMirrorObjectDefinitions.java
- ymer/src/test/java/com/avanza/ymer/YmerMirrorNoClusterPropertiesIntegrationTest.java
* Also, to avoid unnecessary warning logs in tests, only execute `initializeStatistics()` if persisting of instance id is enabled for any mirrored object.
* This is also applied to another warning log about current number of partitions and scheduling of persisted instance id calculation.
> TP-937: Do not fail application context if `initializeStatistics()` fails

- ymer/src/main/java/com/avanza/ymer/MirroredObject.java
- ymer/src/main/java/com/avanza/ymer/MirroredObjectDefinition.java
- ymer/src/main/java/com/avanza/ymer/MirroredObjectDefinitionsOverride.java
- ymer/src/main/java/com/avanza/ymer/PersistInstanceIdDefinition.java
- ymer/src/main/java/com/avanza/ymer/ReloadableYmerProperties.java
- ymer/src/test/java/com/avanza/ymer/MirroredObjectLoaderTest.java
- ymer/src/test/java/com/avanza/ymer/MirroredObjectTest.java
- ymer/src/test/java/com/avanza/ymer/MirroredObjectWriterTest.java
- ymer/src/test/java/com/avanza/ymer/TestSpaceMirrorObjectDefinitions.java
* No functionality is changed, this only changes the configuration code
* The current format does not align well with the other configuration available
* In particular, a `persistInstanceId(boolean enabled)` method will make this more like the others
* More detailed properties can be accessed through a method accepting a `Consumer`
An example of the new config format can be seen in [TestSpaceMirrorObjectDefinitions](https://github.com/AvanzaBank/ymer/blob/6a902337f2a049e7fec79ef60bb7c4a8e666922d/ymer/src/test/java/com/avanza/ymer/TestSpaceMirrorObjectDefinitions.java)
> TP-938: Align configuration format to other config in `MirroredObjectDefinition`

- ymer/src/main/java/com/avanza/ymer/MirroredObjectLoader.java
- ymer/src/main/java/com/avanza/ymer/PersistedInstanceIdCalculationService.java
- ymer/src/main/java/com/avanza/ymer/PersistedInstanceIdUtil.java
* `_instanceId` fields and `_routingKey` is only used when loading data, and is not needed by Ymer in Java code
* By excluding these fields, network traffic from mongodb can be reduced by a (very) small amount for each document
> TP-939: Exclude unused fields when loading by instance id

- ymer/src/main/java/com/avanza/ymer/MirroredObjectLoader.java
- ymer/src/main/java/com/avanza/ymer/PersistedInstanceIdCalculationService.java
- ymer/src/main/java/com/avanza/ymer/YmerSpaceSynchronizationEndpoint.java
* Replace `Begin loadAllObjects` log with a log that also displays which loading method is used.
* Add collection being operated on in some calculation job logs
> TP-939: Small log adjustments to clarify which loading method is used

- ymer/src/main/java/com/avanza/ymer/PersistedInstanceIdCalculationService.java
- ymer/src/main/java/com/avanza/ymer/PersistedInstanceIdStatistics.java
- ymer/src/main/java/com/avanza/ymer/YmerSpaceSynchronizationEndpoint.java
* Always call `calculationCompleted()` for statistics even if job finishes with exception, so `isCalculationInProgress()` won't return `true` if the job ends with an exception.
* Also name thread created by `YmerSpaceSynchronizationEndpoint`
> TP-939: Always finalize statistics when job is finished

- ymer/src/main/java/com/avanza/ymer/BasicDbObjectCompatibility.java
- ymer/src/main/java/com/avanza/ymer/BsonDocumentPatch.java
- ymer/src/main/java/com/avanza/ymer/DocumentPatch.java
- ymer/src/main/java/com/avanza/ymer/MirroredObjectLoader.java
- ymer/src/test/java/com/avanza/ymer/BasicDbObjectCompatibilityTest.java
- ymer/src/test/java/com/avanza/ymer/BsonDocumentPatchTest.java
* When converting `org.bson.Document` to `com.mongodb.BasicDBObject`, also convert all field values in the same way, not only the top-level object.
* Reason for changing is to support documentpatches that use `DocumentPatch` instead of `BsonDocumentPatch`, that handle documents with complex datatypes.
> TP-1047: Deep-copy `BasicDBObject` for document-patch compatibility

- ymer/src/main/java/com/avanza/ymer/MirroredObject.java
- ymer/src/test/java/com/avanza/ymer/PersistedInstanceIdCalculationServiceTest.java
- ymer/src/test/java/com/avanza/ymer/TestSpaceMirrorObjectDefinitions.java
- ymer/src/test/java/com/avanza/ymer/TestSpaceObjectWithCustomRoutingKey.java
- ymer/src/test/java/com/avanza/ymer/YmerMirrorIntegrationTest.java
* Prevents the exeption listed below, which happens when deleting a space object whose routing key is null.
* The routing key can be null if the space object defines another routing key than the id, and performs a delete-by-id operation.
```
java.lang.NullPointerException: null
at com.avanza.ymer.util.GigaSpacesInstanceIdUtil.getInstanceId(GigaSpacesInstanceIdUtil.java:48) ~[ymer-3.0.5.jar:3.0.5]
at com.avanza.ymer.MirroredObject.lambda$setInstanceIdFields$0(MirroredObject.java:151) ~[ymer-3.0.5.jar:3.0.5]
at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
at com.avanza.ymer.MirroredObject.setInstanceIdFields(MirroredObject.java:150) ~[ymer-3.0.5.jar:3.0.5]
at com.avanza.ymer.MirroredObject.setDocumentAttributes(MirroredObject.java:128) ~[ymer-3.0.5.jar:3.0.5]
at …
```
> TP-1181: Prevent NPE when deleting `persistInstanceId` objs

- ymer/src/main/java/com/avanza/ymer/BulkMirroredObjectWriter.java
- ymer/src/main/java/com/avanza/ymer/MirroredObjectWriter.java
- ymer/src/main/java/com/avanza/ymer/RethrowsTransientDocumentWriteExceptionHandler.java
- ymer/src/main/java/com/avanza/ymer/YmerSpaceSynchronizationEndpoint.java
- ymer/src/test/java/com/avanza/ymer/BulkMirroredObjectWriterTest.java
- ymer/src/test/java/com/avanza/ymer/FakeDocumentCollection.java
- ymer/src/test/java/com/avanza/ymer/MirrorEnvironment.java
- ymer/src/test/java/com/avanza/ymer/MirroredObjectWriterTest.java
- ymer/src/test/java/com/avanza/ymer/YmerBulkMirrorIntegrationTest.java
- ymer/src/test/java/com/avanza/ymer/YmerMirrorIntegrationTestBase.java
- ymer/src/test/java/com/avanza/ymer/helper/FakeBatchData.java
- ymer/src/test/java/com/avanza/ymer/helper/FakeBulkItem.java
* Adds statistics from https://github.com/AvanzaBank/ymer/pull/96 to the new `BulkMirroredObjectWriter`
* Handle counting failure statistics for document conversion when retries occur
* Add tests verifying the statistics are calculated correctly
---
Targets https://github.com/AvanzaBank/ymer/pull/97 as that branch can't be merged to `main` branch without these fixes. I created this as a separate PR to not any more logic to review in the earlier PR.
> TP-1209: Add statistics to BulkMirroredObjectWriter

- ymer/src/main/java/com/avanza/ymer/BulkMirroredObjectWriter.java
* This warning did not work out, as this occurs when object with same data is written to space. This warning just creates unnecessary clutter.
* Keep it on `debug` level so it can be turned on if needed to investigate for some reason.
> TP-1209: Remove expected warning log

- ymer/src/main/java/com/avanza/ymer/MirroredObjectWriter.java
- ymer/src/main/java/com/avanza/ymer/ReloadableYmerProperties.java
- ymer/src/main/java/com/avanza/ymer/YmerSpaceSynchronizationEndpoint.java
- ymer/src/test/java/com/avanza/ymer/MirroredObjectWriterTest.java
- ymer/src/test/java/com/avanza/ymer/YmerNonBulkMirrorIntegrationTest.java
* Using bulkWrite for writing is now the default option
* Deprecated the old `MirroredObjectWriter`
> TP-1229: Make using bulkWrite default

- ymer/src/main/java/com/avanza/ymer/BulkMirroredObjectWriter.java
- ymer/src/test/java/com/avanza/ymer/TestSpaceMirrorObjectDefinitions.java
- ymer/src/test/java/com/avanza/ymer/YmerMirrorIntegrationTestBase.java
- ymer/src/test/java/com/avanza/ymer/space/ComplexId.java
- ymer/src/test/java/com/avanza/ymer/space/SpaceObjectWithComplexKey.java
* Complex keys would result in an exception thrown by `bson.getId().asString()`
* Instead, just use `toString()` conversion
* Also, add an extra guard to `checkBulkResultForWarnings` to not propagate errors from this method
> TP-1249: Fix handling of complex key in bulkWrite

- pom.xml
- ymer/pom.xml
This removes transitive dependencies on:
* `org.xerial:sqlite-jdbc` (this is one huge artifact)
* `org.junit.jupiter:junit-jupiter-params` (this should not be a compile-scoped dependency)
* `com.github.oshi:oshi-core` (unused and unnecessary)
Also:
* Added missing dependency to `junit-jupiter` (was previously relying on transitive junit-jupiter from gigaspaces).
* Bumped version of `gs-test` to latest.
> TP-1276: Remove unnecessary dependencies

- examples/example-tests/pom.xml
- examples/example-tests/src/test/java/example/tests/InMemoryMongoServer.java
- examples/example-tests/src/test/java/example/tests/InitialLoadTest.java
- examples/example-tests/src/test/java/example/tests/SpaceObjectWriteSynchronizationTest.java
- pom.xml
* Fongo does not work with version 3.8.2, hence the test implementation is changed to use mongo-java-server instead.
> TP-1295: Update mongo-java-driver to 3.8.2
